### ISSUE TITLE
Schedule of releasing WFLW dataset

### ISSUE THREAD

**Issue by dongwu92** [wywu/LAB#1]
Hi,
  Thank you for your great work~
  Could you please inform us the schedule of releasing the WFLW dataset? Thank you!

**Comment by wywu** [comment]
Due to the audits of our company, code and WFLW dataset cannot be released immediately.
We hope to release them no later than the end of July.

**Comment by CatLoves** [comment]
Great works! 
 Looking forward to your brilliant source code and WFLW dataset !

**Comment by whu-lyh** [comment]
wao， i can't wait to enjoy your model~~~

**Comment by jiangtaoo2333** [comment]
waiting code

**Comment by wywu** [comment]
Hi,

Thanks for your interests! 
The WFLW dataset, code, and models are all publicly available now.
WFLW dataset: https://wywu.github.io/projects/LAB/WFLW.html
Code and models:https://github.com/wywu/LAB

Best,
Wayne

**Comment by whu-lyh** [comment]
thank you very much~
