### ISSUE TITLE
face landmark detection is frame by frame?

### ISSUE THREAD

**Issue by zsf23** [wywu/LAB#11]
@wywu Thanks for sharing great work. From the demo video, it seems a little shaking in face landmarks. Are the landmarks detected frame by frame? Is there any method to keep landmarks stable  when process video?

**Comment by wywu** [comment]
Hi,

Yes. The landmarks are detected frame by frame. This work is focused on landmark detection on the static image. For video, we suggest to include temporal information during training and take it as our future work.

Best,
Wayne
