### ISSUE TITLE
Question for running the test on WLFW with the final model

### ISSUE THREAD

**Issue by hchc0704** [wywu/LAB#19]
Dear author,
        after running the file "run_test_on_wflw.sh final",the testing result file "pred_release.txt" is the empty file,I can't find where is the problem,whether the setting of "alignment_tools.cpp" have some mistakes?could you give me some suggests,thanks!

I1021 23:08:56.250052  3648 net.cpp:255] Network initialization done.
I1021 23:08:56.664265  3648 net.cpp:744] Ignoring source layer traindata_layer
I1021 23:08:56.664422  3648 net.cpp:744] Ignoring source layer data_scatter
I1021 23:08:56.664510  3648 net.cpp:744] Ignoring source layer data_scatter_data_scatter_0_split
I1021 23:08:56.762648  3648 net.cpp:744] Ignoring source layer data_scatter/concat
I1021 23:08:56.762770  3648 net.cpp:744] Ignoring source layer data_scatter/prod
I1021 23:08:56.762835  3648 net.cpp:744] Ignoring source layer data_scatter/prob/concat
I1021 23:08:56.786267  3648 net.cpp:744] Ignoring source layer res4_2/bn/gather
I1021 23:08:56.786377  3648 net.cpp:744] Ignoring source layer res4_2/bn/gather/dropout
I1021 23:08:56.798363  3648 net.cpp:744] Ignoring source layer loss_98pt
W1021 23:08:57.063319  3648 net.hpp:41] DEPRECATED: ForwardPrefilled() will be removed in a future version. Use Forward().
Killed
list 7 done
cat: ./dataset/WFLW/WFLW_annotations/list_98pt_test_largepose.txt: No such file or directory
cat: ./evaluation/WFLW/WFLW_final_result/pred_98pt_largepose.txt: No such file or directory
cat: ./evaluation/WFLW/WFLW_final_result/pred_98pt_expression.txt: No such file or directory
cat: ./evaluation/WFLW/WFLW_final_result/pred_98pt_illumination.txt: No such file or directory
cat: ./evaluation/WFLW/WFLW_final_result/pred_98pt_makeup.txt: No such file or directory
cat: ./evaluation/WFLW/WFLW_final_result/pred_98pt_occlusion.txt: No such file or directory
cat: ./evaluation/WFLW/WFLW_final_result/pred_98pt_blur.txt: No such file or directory
cat: ./evaluation/WFLW/WFLW_final_result/pred_98pt_test.txt: No such file or directory

Best,
hchc0704

**Comment by lijianaiml** [comment]
@hchc0704 hi,i got the same error ,how did you solve it?
