### ISSUE TITLE
300w dataset--bbox

### ISSUE THREAD

**Issue by yangyangkiki** [wywu/LAB#26]
Hi,

I am going to repeat your result on 300w dataset and WFLW dataset.

 I found that result of face alignment is sensitive to face bounding box. You mentioned in your paper that all training images are cropped and resized to 256*256 according to provided bounding boxes. WFLW provide bbox in the ann file. But 300W dataset provide two different bounding box. One is  detected by a face detector, and anther is determined by 68 landmarks.

So which bounding box is used in your experiments? Or any other face detector do you use?

Thank you.

Regards,
Kiki

**Comment by hao-qiang** [comment]
Hi @yangyangkiki 
I have a question now, the bbox provided in WFLW is the bounding of face, if I crop face according to this and resize to 256*256, the face will be stretched, and the face figures in paper have extra space around face. How do you process this dataset?
thank!

**Comment by FunkyKoki** [comment]
This is also a question for me, wish you would tell me **how to determine the bbox**, thanks so much!

**Comment by yangyangkiki** [comment]
Hi @hao-qiang 

Unfortunately, this is also a question for me. I did not solve this problem when I want to repeat this experiment. Hope somebody can tell us.
