### ISSUE TITLE
你好，请问Boundary Heatmaps的Truth Heatmap我们是怎么打标得到的，而且打标后有经过什么处理？

### ISSUE THREAD

**Issue by YDS-FOREVER** [wywu/LAB#37]
你好，请问Boundary Heatmaps的Truth Heatmap我们是怎么打标得到的，而且打标后有经过什么处理？例如人体的热点图会经过一个高斯模糊制作一个范围内的truth heatmap概率图。像我们的是怎么处理的？

**Comment by wywu** [comment]
@yangdashi888 Please refer to the paper.
