### ISSUE TITLE
where is the model.prototxt

### ISSUE THREAD

**Issue by YuqiHUO** [wywu/LAB#4]
i cannot find it...

**Comment by wywu** [comment]
Hi,

You can download the pre-trained models and I suppose the "rel.prototxt" is what you refer to.

Best,
Wayne

**Comment by YuqiHUO** [comment]
Thanks.

**Comment by yangyangkiki** [comment]
@YuqiHUO 

Hi ,

I still cannot find 'rel.prototxt', where is the exact place?

Thank you.

Regards,
Kiki

**Comment by YuqiHUO** [comment]
@yangyangkiki 
Hi,
here is the link:
https://wywu.github.io/projects/LAB/support/WFLW_wo_mp.tar.gz for no mpl layers
https://wywu.github.io/projects/LAB/support/WFLW_final.tar.gz for final model

Best,
Yuqi

**Comment by yangyangkiki** [comment]
> @yangyangkiki
> Hi,
> here is the link:
> https://wywu.github.io/projects/LAB/support/WFLW_wo_mp.tar.gz for no mpl layers
> https://wywu.github.io/projects/LAB/support/WFLW_final.tar.gz for final model
> 
> Best,
> Yuqi

@YuqiHUO 
Hi,
Thank u for your kindly reply.

Regards,
Kiki
