### ISSUE TITLE
请问怎么在opencv使用模型文件？

### ISSUE THREAD

**Issue by BenJaminKen** [wywu/LAB#40]
已经有人改成功了，看了下面的文章，还是不知道怎么修改.prototxt文件，请问你能给点提示吗？http://answers.opencv.org/question/202517/dnn-resize_layer-assertion-getmemoryshapes/?answer=205095#post-id-205095

**Comment by BenJaminKen** [comment]
I've done it

**Comment by youthM** [comment]
Hi,介意提供一下你修改成功的模型吗？ @BenJaminKen
