### ISSUE TITLE
How to calculate inter-pupil distance?

### ISSUE THREAD

**Issue by protossw512** [wywu/LAB#6]
I am having trouble on calculating inter-pupil distance, since 68 landmarks does not have points on pupils.
I think there could be two ways to do this:
1. Using the center of eye corners as the center of pupils
2. Using the location averaged by all 6 points around eyes to get the position of pupils
Could you please provide some details on how did you calculate NME?

Thanks

**Comment by wywu** [comment]
Hi,

We use the method-2 for the calculation of inter-pupil distance.

Best,
Wayne

**Comment by protossw512** [comment]
@wywu Thank you so much!

**Comment by yangyangkiki** [comment]
Hi @protossw512 ,

Do you use this way to calculate inter-pupil distance?

In 300w dataset ( https://ibug.doc.ic.ac.uk/resources/300-W/ ) ,for example, 6 coordinates,  (x37, y37),(x38, y38),(x39, y39),(x40,y40), (x41, y41),(x42, y42), consist of right eye. 
 ( (x37 + x38 + x39 +x40 +x41 +x42)/6 , (y37 +y38 + y39 +x40 +x41 +x42)/6  ) is the coordinate of inter-pupil ?

Thank you.

Best,
kiki

**Comment by protossw512** [comment]
Yes I am

**Comment by yangyangkiki** [comment]
Hi @protossw512 ,

Thank you so much!

**Comment by zzk88862** [comment]
hi，I want to confirm my way on calculating inter-pupil distance and inter-ocular distance
my way to do these:

1. about inter-pupil,  6 coordinates, (x37, y37),(x38, y38),(x39, y39),(x40,y40), (x41, y41),(x42, y42), consist of right eye. and  (x43, y43),(x44, y44),(x45, y45),(x46,y46), (x47, y47),(x48, y48), consist of left eye.  xr= ( (x37 + x38 + x39 +x40 +x41 +x42)/6 , (y37 +y38 + y39 +y40 +y41 +y42)/6 ) , xl= ( (x43 + x44 + x45 +x46 +x46 +x48)/6 , (y43 +y44 + y45 +y46 +y47 +y48)/6 ) , the inter-pupil distance is sqrt(square(xr, xl))

2.about inter-ocular, right eye corner is xr = (x37, y37), left eye corner is xl=(x46,y46),  the inter-ocular distance is sqrt(square(xr, xl))
Could you please provide answers about my way on calculating NME?
Thanks

**Comment by zzk88862** [comment]
hi，I want to confirm my way on calculating inter-pupil distance and inter-ocular distance
my way to do these:

1, about inter-pupil, 6 coordinates, (x37, y37),(x38, y38),(x39, y39),(x40,y40), (x41, y41),(x42, y42), consist of right eye. and (x43, y43),(x44, y44),(x45, y45),(x46,y46), (x47, y47),(x48, y48), consist of left eye. xr= ( (x37 + x38 + x39 +x40 +x41 +x42)/6 , (y37 +y38 + y39 +y40 +y41 +y42)/6 ) , xl= ( (x43 + x44 + x45 +x46 +x46 +x48)/6 , (y43 +y44 + y45 +y46 +y47 +y48)/6 ) , the inter-pupil distance is sqrt(square(xr, xl))

2.about inter-ocular, right eye corner is xr = (x37, y37), left eye corner is xl=(x46,y46), the inter-ocular distance is sqrt(square(xr, xl))

Could you please provide answers about my way on calculating NME?
Thanks

**Comment by haiduo** [comment]
> hi，I want to confirm my way on calculating inter-pupil distance and inter-ocular distance
> my way to do these:
> 
> 1, about inter-pupil, 6 coordinates, (x37, y37),(x38, y38),(x39, y39),(x40,y40), (x41, y41),(x42, y42), consist of right eye. and (x43, y43),(x44, y44),(x45, y45),(x46,y46), (x47, y47),(x48, y48), consist of left eye. xr= ( (x37 + x38 + x39 +x40 +x41 +x42)/6 , (y37 +y38 + y39 +y40 +y41 +y42)/6 ) , xl= ( (x43 + x44 + x45 +x46 +x46 +x48)/6 , (y43 +y44 + y45 +y46 +y47 +y48)/6 ) , the inter-pupil distance is sqrt(square(xr, xl))
> 
> 2.about inter-ocular, right eye corner is xr = (x37, y37), left eye corner is xl=(x46,y46), the inter-ocular distance is sqrt(square(xr, xl))
> 
> Could you please provide answers about my way on calculating NME?
> Thanks

I also think so.
