### ISSUE TITLE
Can't build  /tools/alignment_tools.bin

### ISSUE THREAD

**Issue by ghost** [wywu/LAB#7]
Hello, can anybody help me please? I got a wrong message when i build the Modified-caffe for LAB. The error info as follow:

.build_release/tools/alignment_tools.o：在函数‘RunTestOnWFLW() [clone ._omp_fn.0]’中：
alignment_tools.cpp:(.text+0x4f1)：对‘alignment_tools::ConvertImageToBGR(cv::Mat&)’未定义的引用
alignment_tools.cpp:(.text+0x881)：对‘alignment_tools::CalcAffineMatByPose(std::vector<cv::Point_<float>, std::allocator<cv::Point_<float> > > const&, std::vector<cv::Point_<float>, std::allocator<cv::Point_<float> > > const&)’未定义的引用
alignment_tools.cpp:(.text+0xe9e)：对‘alignment_tools::NormalizeImage(cv::Mat&)’未定义的引用
alignment_tools.cpp:(.text+0x1586)：对‘alignment_tools::InvAffinePose(cv::Mat_<float> const&, std::vector<cv::Point_<float>, std::allocator<cv::Point_<float> > > const&)’未定义的引用
alignment_tools.cpp:(.text+0x16b7)：对‘alignment_tools::InvAffinePose(cv::Mat_<float> const&, std::vector<cv::Point_<float>, std::allocator<cv::Point_<float> > > const&)’未定义的引用
alignment_tools.cpp:(.text+0x1cc8)：对‘alignment_tools::ConvertImageToGray(cv::Mat&)’未定义的引用
.build_release/tools/alignment_tools.o：在函数‘RunTestOnWFLW()’中：
alignment_tools.cpp:(.text+0x4552)：对‘alignment_tools::ReadImageLabelList(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&, std::vector<std::vector<float, std::allocator<float> >, std::allocator<std::vector<float, std::allocator<float> > > >&)’未定义的引用
alignment_tools.cpp:(.text+0x4615)：对‘alignment_tools::ReadLabelList(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int const&)’未定义的引用
alignment_tools.cpp:(.text+0x54d9)：对‘alignment_tools::WriteImageLabelList(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::vector<std::vector<float, std::allocator<float> >, std::allocator<std::vector<float, std::allocator<float> > > > const&)’未定义的引用
collect2: error: ld returned 1 exit status
Makefile:628: recipe for target '.build_release/tools/alignment_tools.bin' failed
make: *** [.build_release/tools/alignment_tools.bin] Error 1
make: *** 正在等待未完成的任务....

I have google this error, but i haven't get any helpful info. By the way,  i build the caffe with other enviroment: cuda 9.0, cudnn 7.0, python 3.5, opencv 3.3.1, matlab 2016b.
Thank you very much.

**Comment by uyekt** [comment]
@WeaponLin  How did you solved it?
